### ISSUE TITLE
Bug for PIWIK if Chat Plugin installed

### ISSUE THREAD

**Issue by diginet-md** [VincentLahaye/piwik-chat#20]
We speak about Chat for PIWIK
http://plugins.piwik.org/Chat
https://github.com/VincentLahaye/piwik-chat

1) We installed Chat plugin from Piwik on one of our test web project

2) now there is some problem with chat plugin
Could you please to assist to fix problems (bug)

2.1) Text of message no 1. in PIWIK panel
WARNING: /var/www/analytics/core/Tracker/Settings.php(24): Notice - Undefined variable: isSameFingerprintsAcrossWebsites - Piwik 2.13.1

2.2) Text of message no 1. in PIWIK panel
WARNING: /var/www/analytics/core/Tracker/Settings.php(20): Warning - Missing argument 3 for Piwik\Tracker\Settings::__construct(), called in /var/www/analytics/plugins/Chat/Controller.php on line 135 and defined - Piwik 2.13.1

3) Screenshots with the problems
attached
![piwik-chat-screen-1-1](https://cloud.githubusercontent.com/assets/12524464/7720338/cbd039f2-fed4-11e4-94df-730aa183019d.png)

![piwik-chat-screen-2](https://cloud.githubusercontent.com/assets/12524464/7720372/22071f3e-fed5-11e4-9889-46eaadd31aca.png)

![piwik-chat-screen-3-1](https://cloud.githubusercontent.com/assets/12524464/7720380/2e8f995c-fed5-11e4-9765-949adf318d9e.png)

**Comment by VincentLahaye** [comment]
Fixed with 0.3.1
